package cn.migu.income.pojo;


public class MiguIncomeDiff {

    private Long incomeManagerId;

    private String cycle;

    private String projectId;

    private String projectName;

    private String estimateIncome;

    private String estimateExplain;

    private String estimateOptionsUrl;

    private String eastimateStatus;

    private String realIncome;

    private String realStatus;

    private String realExplain;

    private String realOptionsUrl;

    private String deferenceInIncome;

    private String billingType;

    private String taxpayer;

    private String billingStatus;

    private String income;

    private String incomeStatus;

    private String incomeOptionUrl;

    private String incomeDate;

    private String lasteDate;
    
    private String rn;

    private String auditDept;
    
    private String auditPerson;
    
    private String deptId;
    
    private String deptName;
    
    private String personId;
    
    private String personName;
    
    private String offSet;
    
    public String getRn() {
		return rn;
	}

	public void setRn(String rn) {
		this.rn = rn;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public Long getIncomeManagerId() {
        return incomeManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @param incomeManagerId the value for T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeManagerId(Long incomeManagerId) {
        this.incomeManagerId = incomeManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @param cycle the value for T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @return the value of T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @param projectId the value for T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @param projectName the value for T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEstimateIncome() {
        return estimateIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @param estimateIncome the value for T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEstimateIncome(String estimateIncome) {
        this.estimateIncome = estimateIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @return the value of T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEstimateExplain() {
        return estimateExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @param estimateExplain the value for T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEstimateExplain(String estimateExplain) {
        this.estimateExplain = estimateExplain == null ? null : estimateExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @return the value of T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEstimateOptionsUrl() {
        return estimateOptionsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @param estimateOptionsUrl the value for T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEstimateOptionsUrl(String estimateOptionsUrl) {
        this.estimateOptionsUrl = estimateOptionsUrl == null ? null : estimateOptionsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEastimateStatus() {
        return eastimateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @param eastimateStatus the value for T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEastimateStatus(String eastimateStatus) {
        this.eastimateStatus = eastimateStatus == null ? null : eastimateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealIncome() {
        return realIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @param realIncome the value for T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealIncome(String realIncome) {
        this.realIncome = realIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealStatus() {
        return realStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @param realStatus the value for T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealStatus(String realStatus) {
        this.realStatus = realStatus == null ? null : realStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealExplain() {
        return realExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @param realExplain the value for T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealExplain(String realExplain) {
        this.realExplain = realExplain == null ? null : realExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealOptionsUrl() {
        return realOptionsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @param realOptionsUrl the value for T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealOptionsUrl(String realOptionsUrl) {
        this.realOptionsUrl = realOptionsUrl == null ? null : realOptionsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getDeferenceInIncome() {
        return deferenceInIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @param deferenceInIncome the value for T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setDeferenceInIncome(String deferenceInIncome) {
        this.deferenceInIncome = deferenceInIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getBillingType() {
        return billingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @param billingType the value for T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setBillingType(String billingType) {
        this.billingType = billingType == null ? null : billingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @return the value of T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getTaxpayer() {
        return taxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @param taxpayer the value for T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setTaxpayer(String taxpayer) {
        this.taxpayer = taxpayer == null ? null : taxpayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getBillingStatus() {
        return billingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @param billingStatus the value for T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus == null ? null : billingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME
     *
     * @param income the value for T_MIGU_INCOME_MANAGER.INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncome(String income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncomeStatus() {
        return incomeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @param incomeStatus the value for T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeStatus(String incomeStatus) {
        this.incomeStatus = incomeStatus == null ? null : incomeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncomeOptionUrl() {
        return incomeOptionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @param incomeOptionUrl the value for T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeOptionUrl(String incomeOptionUrl) {
        this.incomeOptionUrl = incomeOptionUrl == null ? null : incomeOptionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @param incomeDate the value for T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeDate(String incomeDate) {
        this.incomeDate = incomeDate == null ? null : incomeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getLasteDate() {
        return lasteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @param lasteDate the value for T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setLasteDate(String lasteDate) {
        this.lasteDate = lasteDate == null ? null : lasteDate.trim();
    }

    
	public String getAuditDept() {
		return auditDept;
	}

	public void setAuditDept(String auditDept) {
		this.auditDept = auditDept == null ? null : auditDept.trim();
	}

	public String getAuditPerson() {
		return auditPerson;
	}

	public void setAuditPerson(String auditPerson) {
		this.auditPerson = auditPerson == null ? null : auditPerson.trim();
	}

	
	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getPersonId() {
		return personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}

	
	public String getOffSet() {
		return offSet;
	}

	public void setOffSet(String offSet) {
		this.offSet = offSet;
	}
	@Override
	public String toString() {
		return "MiguIncomeDiff [incomeManagerId=" + incomeManagerId + ", cycle=" + cycle + ", projectId=" + projectId
				+ ", projectName=" + projectName + ", estimateIncome=" + estimateIncome + ", estimateExplain="
				+ estimateExplain + ", estimateOptionsUrl=" + estimateOptionsUrl + ", eastimateStatus="
				+ eastimateStatus + ", realIncome=" + realIncome + ", realStatus=" + realStatus + ", realExplain="
				+ realExplain + ", realOptionsUrl=" + realOptionsUrl + ", deferenceInIncome=" + deferenceInIncome
				+ ", billingType=" + billingType + ", taxpayer=" + taxpayer + ", billingStatus=" + billingStatus
				+ ", income=" + income + ", incomeStatus=" + incomeStatus + ", incomeOptionUrl=" + incomeOptionUrl
				+ ", incomeDate=" + incomeDate + ", lasteDate=" + lasteDate + ", rn=" + rn + ", auditDept=" + auditDept
				+ ", auditPerson=" + auditPerson + ", deptId=" + deptId + ", deptName=" + deptName + ", personId="
				+ personId + ", personName=" + personName + ", offSet=" + offSet + "]";
	}


}