package cn.migu.income.pojo;

public class MiguIncomeDetail {
	
    private Long incomeDetailId;

    private String incomeManagerId;

   
    private String priceConfigInfoId;

   
    private Double sellingPrice;

   
    private Double porductNumber;

    private String type;

    private String cycle;
    
    private String productId;
    
    private String productName;
   
    public Long getIncomeDetailId() {
        return incomeDetailId;
    }

  
    public String getCycle() {
		return cycle;
	}


	public void setCycle(String cycle) {
		this.cycle = cycle;
	}


	public String getProductId() {
		return productId;
	}


	public void setProductId(String productId) {
		this.productId = productId;
	}


	public String getProductName() {
		return productName;
	}


	public void setProductName(String productName) {
		this.productName = productName;
	}


	public void setIncomeDetailId(Long incomeDetailId) {
        this.incomeDetailId = incomeDetailId;
    }

   
    public String getIncomeManagerId() {
        return incomeManagerId;
    }

  
    public void setIncomeManagerId(String incomeManagerId) {
        this.incomeManagerId = incomeManagerId == null ? null : incomeManagerId.trim();
    }

  
    public String getPriceConfigInfoId() {
        return priceConfigInfoId;
    }

  
    public void setPriceConfigInfoId(String priceConfigInfoId) {
        this.priceConfigInfoId = priceConfigInfoId == null ? null : priceConfigInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_DETAIL.SELLING_PRICE
     *
     * @return the value of T_MIGU_INCOME_DETAIL.SELLING_PRICE
     *
     * @mbg.generated Thu Jul 06 09:51:54 CST 2017
     */
    public Double getSellingPrice() {
        return sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_DETAIL.SELLING_PRICE
     *
     * @param sellingPrice the value for T_MIGU_INCOME_DETAIL.SELLING_PRICE
     *
     * @mbg.generated Thu Jul 06 09:51:54 CST 2017
     */
    public void setSellingPrice(Double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_DETAIL.PORDUCT_NUMBER
     *
     * @return the value of T_MIGU_INCOME_DETAIL.PORDUCT_NUMBER
     *
     * @mbg.generated Thu Jul 06 09:51:54 CST 2017
     */
    public Double getPorductNumber() {
        return porductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_DETAIL.PORDUCT_NUMBER
     *
     * @param porductNumber the value for T_MIGU_INCOME_DETAIL.PORDUCT_NUMBER
     *
     * @mbg.generated Thu Jul 06 09:51:54 CST 2017
     */
    public void setPorductNumber(Double porductNumber) {
        this.porductNumber = porductNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_DETAIL.TYPE
     *
     * @return the value of T_MIGU_INCOME_DETAIL.TYPE
     *
     * @mbg.generated Thu Jul 06 09:51:54 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_DETAIL.TYPE
     *
     * @param type the value for T_MIGU_INCOME_DETAIL.TYPE
     *
     * @mbg.generated Thu Jul 06 09:51:54 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}