package cn.migu.income.pojo;

import java.io.Serializable;

public class MiguUsers implements Serializable {
    /**
     * 注释内容
     */
    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.USER_ID
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.USER_NAME
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.PASSWORD
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.MSISDN
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String msisdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.EMAIL
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.CRTATE_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String crtateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.START_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.END_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.PWD_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String pwdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USERS.LAST_PWD
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    private String lastPwd;
    
    private Long roleId;
    
    private String deptId;
    
    private String deptName;

    private String pricingCommittee;
    
    public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getDeptId() {
		return deptId;
	}

	public void setDeptId(String deptId) {
		this.deptId = deptId;
	}

	public Long getRoleId()
    {
        return roleId;
    }

    public void setRoleId(Long roleId)
    {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.USER_ID
     *
     * @return the value of T_MIGU_USERS.USER_ID
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.USER_ID
     *
     * @param userId the value for T_MIGU_USERS.USER_ID
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.USER_NAME
     *
     * @return the value of T_MIGU_USERS.USER_NAME
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.USER_NAME
     *
     * @param userName the value for T_MIGU_USERS.USER_NAME
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.PASSWORD
     *
     * @return the value of T_MIGU_USERS.PASSWORD
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.PASSWORD
     *
     * @param password the value for T_MIGU_USERS.PASSWORD
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.MSISDN
     *
     * @return the value of T_MIGU_USERS.MSISDN
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.MSISDN
     *
     * @param msisdn the value for T_MIGU_USERS.MSISDN
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setMsisdn(String msisdn) {
        this.msisdn = msisdn == null ? null : msisdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.EMAIL
     *
     * @return the value of T_MIGU_USERS.EMAIL
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.EMAIL
     *
     * @param email the value for T_MIGU_USERS.EMAIL
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.CRTATE_DATE
     *
     * @return the value of T_MIGU_USERS.CRTATE_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getCrtateDate() {
        return crtateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.CRTATE_DATE
     *
     * @param crtateDate the value for T_MIGU_USERS.CRTATE_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setCrtateDate(String crtateDate) {
        this.crtateDate = crtateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.START_DATE
     *
     * @return the value of T_MIGU_USERS.START_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.START_DATE
     *
     * @param startDate the value for T_MIGU_USERS.START_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.END_DATE
     *
     * @return the value of T_MIGU_USERS.END_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.END_DATE
     *
     * @param endDate the value for T_MIGU_USERS.END_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.PWD_DATE
     *
     * @return the value of T_MIGU_USERS.PWD_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getPwdDate() {
        return pwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.PWD_DATE
     *
     * @param pwdDate the value for T_MIGU_USERS.PWD_DATE
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setPwdDate(String pwdDate) {
        this.pwdDate = pwdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USERS.LAST_PWD
     *
     * @return the value of T_MIGU_USERS.LAST_PWD
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public String getLastPwd() {
        return lastPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USERS.LAST_PWD
     *
     * @param lastPwd the value for T_MIGU_USERS.LAST_PWD
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    public void setLastPwd(String lastPwd) {
        this.lastPwd = lastPwd == null ? null : lastPwd.trim();
    }

    
    
	public String getPricingCommittee() {
		return pricingCommittee;
	}

	public void setPricingCommittee(String pricingCommittee) {
		this.pricingCommittee = pricingCommittee;
	}

	@Override
	public String toString() {
		return "MiguUsers [userId=" + userId + ", userName=" + userName + ", password=" + password + ", msisdn="
				+ msisdn + ", email=" + email + ", crtateDate=" + crtateDate + ", startDate=" + startDate + ", endDate="
				+ endDate + ", pwdDate=" + pwdDate + ", lastPwd=" + lastPwd + ", roleId=" + roleId + ", deptId="
				+ deptId + ", deptName=" + deptName + ",pricingCommittee="+pricingCommittee+"]";
	}

    
}