package cn.migu.income.pojo;

public class MiguUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    private Long userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USER_ROLE.USER_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USER_ROLE.USER_ROLE_ID
     *
     * @return the value of T_MIGU_USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    public Long getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USER_ROLE.USER_ROLE_ID
     *
     * @param userRoleId the value for T_MIGU_USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USER_ROLE.USER_ID
     *
     * @return the value of T_MIGU_USER_ROLE.USER_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USER_ROLE.USER_ID
     *
     * @param userId the value for T_MIGU_USER_ROLE.USER_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_USER_ROLE.ROLE_ID
     *
     * @return the value of T_MIGU_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for T_MIGU_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Jan 06 13:57:07 CST 2016
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}