package cn.migu.income.pojo;

import java.util.Date;

import javax.persistence.Transient;

public class MiguSystemOptLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_SYSLOG.USER_ID
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    private String rn;
    
    public String getRn()
    {
        return rn;
    }

    public void setRn(String rn)
    {
        this.rn = rn;
    }

    private String userId;
    private String userName;
    
    //用户姓名单独列一个数据
      @Transient
      public String getUserName()
      {
          return userName;
      }

      public void setUserName(String userName)
      {
          this.userName = userName;
      }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_SYSLOG.LOG_DATE
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    private String logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_SYSLOG.OPERATION
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_SYSLOG.COMMENTS
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    private String comments;
    
    private String userLoginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_SYSLOG.USER_ID
     *
     * @return the value of T_MIGU_SYSLOG.USER_ID
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_SYSLOG.USER_ID
     *
     * @param userId the value for T_MIGU_SYSLOG.USER_ID
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_SYSLOG.LOG_DATE
     *
     * @return the value of T_MIGU_SYSLOG.LOG_DATE
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public String getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_SYSLOG.LOG_DATE
     *
     * @param logDate the value for T_MIGU_SYSLOG.LOG_DATE
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public void setLogDate(String logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_SYSLOG.OPERATION
     *
     * @return the value of T_MIGU_SYSLOG.OPERATION
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_SYSLOG.OPERATION
     *
     * @param operation the value for T_MIGU_SYSLOG.OPERATION
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_SYSLOG.COMMENTS
     *
     * @return the value of T_MIGU_SYSLOG.COMMENTS
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_SYSLOG.COMMENTS
     *
     * @param comments the value for T_MIGU_SYSLOG.COMMENTS
     *
     * @mbggenerated Tue Feb 23 13:59:26 CST 2016
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

	public String getUserLoginIp() {
		return userLoginIp;
	}

	public void setUserLoginIp(String userLoginIp) {
		this.userLoginIp = userLoginIp;
	}

	@Override
	public String toString() {
		return "MiguSystemOptLog [rn=" + rn + ", userId=" + userId + ", userName=" + userName + ", logDate=" + logDate
				+ ", operation=" + operation + ", comments=" + comments + ", userLoginIp=" + userLoginIp + "]";
	}


   
    
}