package cn.migu.income.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MiguProjectBudgetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public MiguProjectBudgetExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("PROJECT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("PROJECT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(String value) {
            addCriterion("PROJECT_ID =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(String value) {
            addCriterion("PROJECT_ID <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(String value) {
            addCriterion("PROJECT_ID >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROJECT_ID >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(String value) {
            addCriterion("PROJECT_ID <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(String value) {
            addCriterion("PROJECT_ID <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLike(String value) {
            addCriterion("PROJECT_ID like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotLike(String value) {
            addCriterion("PROJECT_ID not like", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<String> values) {
            addCriterion("PROJECT_ID in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<String> values) {
            addCriterion("PROJECT_ID not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(String value1, String value2) {
            addCriterion("PROJECT_ID between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(String value1, String value2) {
            addCriterion("PROJECT_ID not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andBudgetYearIsNull() {
            addCriterion("BUDGET_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andBudgetYearIsNotNull() {
            addCriterion("BUDGET_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetYearEqualTo(String value) {
            addCriterion("BUDGET_YEAR =", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearNotEqualTo(String value) {
            addCriterion("BUDGET_YEAR <>", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearGreaterThan(String value) {
            addCriterion("BUDGET_YEAR >", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_YEAR >=", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearLessThan(String value) {
            addCriterion("BUDGET_YEAR <", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_YEAR <=", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearLike(String value) {
            addCriterion("BUDGET_YEAR like", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearNotLike(String value) {
            addCriterion("BUDGET_YEAR not like", value, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearIn(List<String> values) {
            addCriterion("BUDGET_YEAR in", values, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearNotIn(List<String> values) {
            addCriterion("BUDGET_YEAR not in", values, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearBetween(String value1, String value2) {
            addCriterion("BUDGET_YEAR between", value1, value2, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetYearNotBetween(String value1, String value2) {
            addCriterion("BUDGET_YEAR not between", value1, value2, "budgetYear");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawIsNull() {
            addCriterion("BUDGET_DEPT_DRAW is null");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawIsNotNull() {
            addCriterion("BUDGET_DEPT_DRAW is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawEqualTo(String value) {
            addCriterion("BUDGET_DEPT_DRAW =", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawNotEqualTo(String value) {
            addCriterion("BUDGET_DEPT_DRAW <>", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawGreaterThan(String value) {
            addCriterion("BUDGET_DEPT_DRAW >", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_DEPT_DRAW >=", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawLessThan(String value) {
            addCriterion("BUDGET_DEPT_DRAW <", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_DEPT_DRAW <=", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawLike(String value) {
            addCriterion("BUDGET_DEPT_DRAW like", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawNotLike(String value) {
            addCriterion("BUDGET_DEPT_DRAW not like", value, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawIn(List<String> values) {
            addCriterion("BUDGET_DEPT_DRAW in", values, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawNotIn(List<String> values) {
            addCriterion("BUDGET_DEPT_DRAW not in", values, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawBetween(String value1, String value2) {
            addCriterion("BUDGET_DEPT_DRAW between", value1, value2, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptDrawNotBetween(String value1, String value2) {
            addCriterion("BUDGET_DEPT_DRAW not between", value1, value2, "budgetDeptDraw");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseIsNull() {
            addCriterion("BUDGET_DEPT_USE is null");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseIsNotNull() {
            addCriterion("BUDGET_DEPT_USE is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseEqualTo(String value) {
            addCriterion("BUDGET_DEPT_USE =", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseNotEqualTo(String value) {
            addCriterion("BUDGET_DEPT_USE <>", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseGreaterThan(String value) {
            addCriterion("BUDGET_DEPT_USE >", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_DEPT_USE >=", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseLessThan(String value) {
            addCriterion("BUDGET_DEPT_USE <", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_DEPT_USE <=", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseLike(String value) {
            addCriterion("BUDGET_DEPT_USE like", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseNotLike(String value) {
            addCriterion("BUDGET_DEPT_USE not like", value, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseIn(List<String> values) {
            addCriterion("BUDGET_DEPT_USE in", values, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseNotIn(List<String> values) {
            addCriterion("BUDGET_DEPT_USE not in", values, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseBetween(String value1, String value2) {
            addCriterion("BUDGET_DEPT_USE between", value1, value2, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetDeptUseNotBetween(String value1, String value2) {
            addCriterion("BUDGET_DEPT_USE not between", value1, value2, "budgetDeptUse");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberIsNull() {
            addCriterion("BUDGET_PROJECT_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberIsNotNull() {
            addCriterion("BUDGET_PROJECT_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER =", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberNotEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER <>", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberGreaterThan(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER >", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER >=", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberLessThan(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER <", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER <=", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberLike(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER like", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberNotLike(String value) {
            addCriterion("BUDGET_PROJECT_NUMBER not like", value, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberIn(List<String> values) {
            addCriterion("BUDGET_PROJECT_NUMBER in", values, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberNotIn(List<String> values) {
            addCriterion("BUDGET_PROJECT_NUMBER not in", values, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberBetween(String value1, String value2) {
            addCriterion("BUDGET_PROJECT_NUMBER between", value1, value2, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNumberNotBetween(String value1, String value2) {
            addCriterion("BUDGET_PROJECT_NUMBER not between", value1, value2, "budgetProjectNumber");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameIsNull() {
            addCriterion("BUDGET_PROJECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameIsNotNull() {
            addCriterion("BUDGET_PROJECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NAME =", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameNotEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NAME <>", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameGreaterThan(String value) {
            addCriterion("BUDGET_PROJECT_NAME >", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NAME >=", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameLessThan(String value) {
            addCriterion("BUDGET_PROJECT_NAME <", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_PROJECT_NAME <=", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameLike(String value) {
            addCriterion("BUDGET_PROJECT_NAME like", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameNotLike(String value) {
            addCriterion("BUDGET_PROJECT_NAME not like", value, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameIn(List<String> values) {
            addCriterion("BUDGET_PROJECT_NAME in", values, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameNotIn(List<String> values) {
            addCriterion("BUDGET_PROJECT_NAME not in", values, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameBetween(String value1, String value2) {
            addCriterion("BUDGET_PROJECT_NAME between", value1, value2, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetProjectNameNotBetween(String value1, String value2) {
            addCriterion("BUDGET_PROJECT_NAME not between", value1, value2, "budgetProjectName");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeIsNull() {
            addCriterion("BUDGET_SUBJECT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeIsNotNull() {
            addCriterion("BUDGET_SUBJECT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeEqualTo(String value) {
            addCriterion("BUDGET_SUBJECT_CODE =", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeNotEqualTo(String value) {
            addCriterion("BUDGET_SUBJECT_CODE <>", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeGreaterThan(String value) {
            addCriterion("BUDGET_SUBJECT_CODE >", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_SUBJECT_CODE >=", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeLessThan(String value) {
            addCriterion("BUDGET_SUBJECT_CODE <", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_SUBJECT_CODE <=", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeLike(String value) {
            addCriterion("BUDGET_SUBJECT_CODE like", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeNotLike(String value) {
            addCriterion("BUDGET_SUBJECT_CODE not like", value, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeIn(List<String> values) {
            addCriterion("BUDGET_SUBJECT_CODE in", values, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeNotIn(List<String> values) {
            addCriterion("BUDGET_SUBJECT_CODE not in", values, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeBetween(String value1, String value2) {
            addCriterion("BUDGET_SUBJECT_CODE between", value1, value2, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetSubjectCodeNotBetween(String value1, String value2) {
            addCriterion("BUDGET_SUBJECT_CODE not between", value1, value2, "budgetSubjectCode");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountIsNull() {
            addCriterion("BUDGET_AVAILABLE_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountIsNotNull() {
            addCriterion("BUDGET_AVAILABLE_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountEqualTo(BigDecimal value) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT =", value, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountNotEqualTo(BigDecimal value) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT <>", value, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountGreaterThan(BigDecimal value) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT >", value, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT >=", value, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountLessThan(BigDecimal value) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT <", value, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT <=", value, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountIn(List<BigDecimal> values) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT in", values, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountNotIn(List<BigDecimal> values) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT not in", values, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT between", value1, value2, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetAvailableAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUDGET_AVAILABLE_AMOUNT not between", value1, value2, "budgetAvailableAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountIsNull() {
            addCriterion("BUDGET_TOTAL_AMOUNT is null");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountIsNotNull() {
            addCriterion("BUDGET_TOTAL_AMOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountEqualTo(BigDecimal value) {
            addCriterion("BUDGET_TOTAL_AMOUNT =", value, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountNotEqualTo(BigDecimal value) {
            addCriterion("BUDGET_TOTAL_AMOUNT <>", value, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountGreaterThan(BigDecimal value) {
            addCriterion("BUDGET_TOTAL_AMOUNT >", value, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BUDGET_TOTAL_AMOUNT >=", value, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountLessThan(BigDecimal value) {
            addCriterion("BUDGET_TOTAL_AMOUNT <", value, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BUDGET_TOTAL_AMOUNT <=", value, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountIn(List<BigDecimal> values) {
            addCriterion("BUDGET_TOTAL_AMOUNT in", values, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountNotIn(List<BigDecimal> values) {
            addCriterion("BUDGET_TOTAL_AMOUNT not in", values, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUDGET_TOTAL_AMOUNT between", value1, value2, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetTotalAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BUDGET_TOTAL_AMOUNT not between", value1, value2, "budgetTotalAmount");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdIsNull() {
            addCriterion("BUDGET_RESULT_ID is null");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdIsNotNull() {
            addCriterion("BUDGET_RESULT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdEqualTo(String value) {
            addCriterion("BUDGET_RESULT_ID =", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdNotEqualTo(String value) {
            addCriterion("BUDGET_RESULT_ID <>", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdGreaterThan(String value) {
            addCriterion("BUDGET_RESULT_ID >", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdGreaterThanOrEqualTo(String value) {
            addCriterion("BUDGET_RESULT_ID >=", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdLessThan(String value) {
            addCriterion("BUDGET_RESULT_ID <", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdLessThanOrEqualTo(String value) {
            addCriterion("BUDGET_RESULT_ID <=", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdLike(String value) {
            addCriterion("BUDGET_RESULT_ID like", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdNotLike(String value) {
            addCriterion("BUDGET_RESULT_ID not like", value, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdIn(List<String> values) {
            addCriterion("BUDGET_RESULT_ID in", values, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdNotIn(List<String> values) {
            addCriterion("BUDGET_RESULT_ID not in", values, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdBetween(String value1, String value2) {
            addCriterion("BUDGET_RESULT_ID between", value1, value2, "budgetResultId");
            return (Criteria) this;
        }

        public Criteria andBudgetResultIdNotBetween(String value1, String value2) {
            addCriterion("BUDGET_RESULT_ID not between", value1, value2, "budgetResultId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 07 17:46:25 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MIGU_PROJECT_BUDGET
     *
     * @mbg.generated Mon Aug 07 17:46:25 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}