package cn.migu.income.pojo;

import java.util.Comparator;
import java.util.Date;

public class MiguFunc
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_ID
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private Long funcId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_PID
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private Long funcPid;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_NAME
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private String funcName;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_PAGE_SRC
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private String funcPageSrc;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_ORDER
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private Long funcOrder;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_IS_IFRAME
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private Short funcIsIframe;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.CRTATE_DATE
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private Date crtateDate;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC.FUNC_PAGE_SRC
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    private String funcIconClass;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.FUNC_ID
     *
     * @return the value of T_MIGU_FUNC.FUNC_ID
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public Long getFuncId()
    {
        return funcId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.FUNC_ID
     *
     * @param funcId the value for T_MIGU_FUNC.FUNC_ID
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setFuncId(Long funcId)
    {
        this.funcId = funcId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.FUNC_PID
     *
     * @return the value of T_MIGU_FUNC.FUNC_PID
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public Long getFuncPid()
    {
        return funcPid;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.FUNC_PID
     *
     * @param funcPid the value for T_MIGU_FUNC.FUNC_PID
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setFuncPid(Long funcPid)
    {
        this.funcPid = funcPid;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.FUNC_NAME
     *
     * @return the value of T_MIGU_FUNC.FUNC_NAME
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public String getFuncName()
    {
        return funcName;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.FUNC_NAME
     *
     * @param funcName the value for T_MIGU_FUNC.FUNC_NAME
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setFuncName(String funcName)
    {
        this.funcName = funcName == null ? null : funcName.trim();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.FUNC_PAGE_SRC
     *
     * @return the value of T_MIGU_FUNC.FUNC_PAGE_SRC
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public String getFuncPageSrc()
    {
        return funcPageSrc;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.FUNC_PAGE_SRC
     *
     * @param funcPageSrc the value for T_MIGU_FUNC.FUNC_PAGE_SRC
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setFuncPageSrc(String funcPageSrc)
    {
        this.funcPageSrc = funcPageSrc;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.FUNC_ORDER
     *
     * @return the value of T_MIGU_FUNC.FUNC_ORDER
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public Long getFuncOrder()
    {
        return funcOrder;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.FUNC_ORDER
     *
     * @param funcOrder the value for T_MIGU_FUNC.FUNC_ORDER
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setFuncOrder(Long funcOrder)
    {
        this.funcOrder = funcOrder;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.FUNC_IS_IFRAME
     *
     * @return the value of T_MIGU_FUNC.FUNC_IS_IFRAME
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public Short getFuncIsIframe()
    {
        return funcIsIframe;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.FUNC_IS_IFRAME
     *
     * @param funcIsIframe the value for T_MIGU_FUNC.FUNC_IS_IFRAME
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setFuncIsIframe(Short funcIsIframe)
    {
        this.funcIsIframe = funcIsIframe;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC.CRTATE_DATE
     *
     * @return the value of T_MIGU_FUNC.CRTATE_DATE
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public Date getCrtateDate()
    {
        return crtateDate;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC.CRTATE_DATE
     *
     * @param crtateDate the value for T_MIGU_FUNC.CRTATE_DATE
     *
     * @mbggenerated Wed Dec 30 11:13:01 CST 2015
     */
    public void setCrtateDate(Date crtateDate)
    {
        this.crtateDate = crtateDate;
    }
    
    public String getFuncIconClass()
    {
        return funcIconClass;
    }
    
    public void setFuncIconClass(String funcIconClass)
    {
        this.funcIconClass = funcIconClass;
    }
    
    @Override
    public String toString()
    {
        return " funcId:" + funcId + ", funcPid:" + funcPid + ", funcName:" + funcName + ", funcPageSrc:" + funcPageSrc
            + ", funcOrder:" + funcOrder + ", funcIsIframe:" + funcIsIframe + ", crtateDate:" + crtateDate
            + ", funcIconClass:" + funcIconClass;
    }
    
    public static class ComparatorMiguFunc implements Comparator<MiguFunc>
    {
        @Override
        public int compare(MiguFunc func0, MiguFunc func1)
        {
            int thislv = func0.getFuncId().compareTo(func1.getFuncId());
            if (thislv == 0)
            {
                return func0.getFuncId().compareTo(func1.getFuncId());
            }
            else
            {
                return thislv;
            }
        }
    }
}