package cn.migu.income.pojo;

public class MiguFuncRole
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC_ROLE.FUNC_ROLE_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    private Long funcRoleId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC_ROLE.FUNC_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    private Long funcId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    private Long roleId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_FUNC_ROLE.FLAG
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    private Short flag;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC_ROLE.FUNC_ROLE_ID
     *
     * @return the value of T_MIGU_FUNC_ROLE.FUNC_ROLE_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public Long getFuncRoleId()
    {
        return funcRoleId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC_ROLE.FUNC_ROLE_ID
     *
     * @param funcRoleId the value for T_MIGU_FUNC_ROLE.FUNC_ROLE_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public void setFuncRoleId(Long funcRoleId)
    {
        this.funcRoleId = funcRoleId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC_ROLE.FUNC_ID
     *
     * @return the value of T_MIGU_FUNC_ROLE.FUNC_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public Long getFuncId()
    {
        return funcId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC_ROLE.FUNC_ID
     *
     * @param funcId the value for T_MIGU_FUNC_ROLE.FUNC_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public void setFuncId(Long funcId)
    {
        this.funcId = funcId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC_ROLE.ROLE_ID
     *
     * @return the value of T_MIGU_FUNC_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public Long getRoleId()
    {
        return roleId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC_ROLE.ROLE_ID
     *
     * @param roleId the value for T_MIGU_FUNC_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public void setRoleId(Long roleId)
    {
        this.roleId = roleId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_FUNC_ROLE.FLAG
     *
     * @return the value of T_MIGU_FUNC_ROLE.FLAG
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public Short getFlag()
    {
        return flag;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_FUNC_ROLE.FLAG
     *
     * @param flag the value for T_MIGU_FUNC_ROLE.FLAG
     *
     * @mbggenerated Fri Jan 08 13:56:19 CST 2016
     */
    public void setFlag(Short flag)
    {
        this.flag = flag;
    }
    
    @Override
    public String toString()
    {
        return " funcRoleId:" + funcRoleId + ", funcId:" + funcId + ", roleId:" + roleId + ", flag:" + flag;
    }
}