package cn.migu.income.pojo;


public class MiguIncomeManager {
   
    private Long incomeManagerId;

  
    private String cycle;

   
    private String projectId;

  
    private String projectName;

  
    private Double estimateIncome;

  
    private String estimateExplain;

  
    private String estimateOptionsUrl;

  
    private String eastimateStatus;

  
    private Double realIncome;

   
    private String realStatus;

    
    private String realExplain;

  
    private String realOptionsUrl;

   
    private Double deferenceInIncome;

  
    private String billingType;

 
    private String taxpayer;

  
    private String billingStatus;

  
    private Double income;

  
    private String incomeStatus;

   
    private String incomeOptionUrl;

  
    private String incomeDate;

   
    private String lasteDate;
    
    private String rn;

    private String auditDept;
    
    private String auditPerson;
    
    private String fileName;
    
    private String remark;

    private String billingTime;

    private String billingKey;

    private String offset;
    
    private Double estimateIncomeTax;
  
    private Double estimateExclusiveTax;
    
    private Double estimateAmount;
    
    private Double realIncomeTax;
    
    private Double realExclusiveTax;
    
    private Double realAmount;
    
    private String isNeedBill;
    
    private String mergeStatus;
    
    private String mergeId;
    
    private String incomeClass;
    private String className;
    private String deptCode;
    private String incomeSection;
    private String sectionName;
    private String deptName;
    private String userName;
    
    private String bzCycle;
    private String bzCycleReal;
    
    private Integer row;
    
    public String getIncomeClass() {
		return incomeClass;
	}

	public void setIncomeClass(String incomeClass) {
		this.incomeClass = incomeClass;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getDeptCode() {
		return deptCode;
	}

	public void setDeptCode(String deptCode) {
		this.deptCode = deptCode;
	}

	public String getIncomeSection() {
		return incomeSection;
	}

	public void setIncomeSection(String incomeSection) {
		this.incomeSection = incomeSection;
	}

	public String getSectionName() {
		return sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getRow() {
		return row;
	}

	public void setRow(Integer row) {
		this.row = row;
	}

	public String getMergeStatus() {
		return mergeStatus;
	}

	public void setMergeStatus(String mergeStatus) {
		this.mergeStatus = mergeStatus;
	}

	public String getMergeId() {
		return mergeId;
	}

	public void setMergeId(String mergeId) {
		this.mergeId = mergeId;
	}

	public String getOffset() {
		return offset;
	}

	public void setOffset(String offset) {
		this.offset = offset;
	}

	public String getBillingTime() {
        return billingTime;
    }

    public void setBillingTime(String billingTime) {
        this.billingTime = billingTime;
    }

    public String getBillingKey() {
        return billingKey;
    }

    public void setBillingKey(String billingKey) {
        this.billingKey = billingKey;
    }

    public String getRn() {
		return rn;
	}

	public void setRn(String rn) {
		this.rn = rn;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public Long getIncomeManagerId() {
        return incomeManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @param incomeManagerId the value for T_MIGU_INCOME_MANAGER.INCOME_MANAGER_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeManagerId(Long incomeManagerId) {
        this.incomeManagerId = incomeManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @param cycle the value for T_MIGU_INCOME_MANAGER.CYCLE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @return the value of T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @param projectId the value for T_MIGU_INCOME_MANAGER.PROJECT_ID
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @param projectName the value for T_MIGU_INCOME_MANAGER.PROJECT_NAME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public Double getEstimateIncome() {
        return estimateIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @param estimateIncome the value for T_MIGU_INCOME_MANAGER.ESTIMATE_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEstimateIncome(Double estimateIncome) {
        this.estimateIncome = estimateIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @return the value of T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEstimateExplain() {
        return estimateExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @param estimateExplain the value for T_MIGU_INCOME_MANAGER.ESTIMATE_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEstimateExplain(String estimateExplain) {
        this.estimateExplain = estimateExplain == null ? null : estimateExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @return the value of T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEstimateOptionsUrl() {
        return estimateOptionsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @param estimateOptionsUrl the value for T_MIGU_INCOME_MANAGER.ESTIMATE_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEstimateOptionsUrl(String estimateOptionsUrl) {
        this.estimateOptionsUrl = estimateOptionsUrl == null ? null : estimateOptionsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getEastimateStatus() {
        return eastimateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @param eastimateStatus the value for T_MIGU_INCOME_MANAGER.EASTIMATE_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setEastimateStatus(String eastimateStatus) {
        this.eastimateStatus = eastimateStatus == null ? null : eastimateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public Double getRealIncome() {
        return realIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @param realIncome the value for T_MIGU_INCOME_MANAGER.REAL_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealIncome(Double realIncome) {
        this.realIncome = realIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealStatus() {
        return realStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @param realStatus the value for T_MIGU_INCOME_MANAGER.REAL_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealStatus(String realStatus) {
        this.realStatus = realStatus == null ? null : realStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealExplain() {
        return realExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @param realExplain the value for T_MIGU_INCOME_MANAGER.REAL_EXPLAIN
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealExplain(String realExplain) {
        this.realExplain = realExplain == null ? null : realExplain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @return the value of T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getRealOptionsUrl() {
        return realOptionsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @param realOptionsUrl the value for T_MIGU_INCOME_MANAGER.REAL_OPTIONS_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setRealOptionsUrl(String realOptionsUrl) {
        this.realOptionsUrl = realOptionsUrl == null ? null : realOptionsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public Double getDeferenceInIncome() {
        return deferenceInIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @param deferenceInIncome the value for T_MIGU_INCOME_MANAGER.DEFERENCE_IN_INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setDeferenceInIncome(Double deferenceInIncome) {
        this.deferenceInIncome = deferenceInIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getBillingType() {
        return billingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @param billingType the value for T_MIGU_INCOME_MANAGER.BILLING_TYPE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setBillingType(String billingType) {
        this.billingType = billingType == null ? null : billingType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @return the value of T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getTaxpayer() {
        return taxpayer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @param taxpayer the value for T_MIGU_INCOME_MANAGER.TAXPAYER
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setTaxpayer(String taxpayer) {
        this.taxpayer = taxpayer == null ? null : taxpayer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getBillingStatus() {
        return billingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @param billingStatus the value for T_MIGU_INCOME_MANAGER.BILLING_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus == null ? null : billingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public Double getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME
     *
     * @param income the value for T_MIGU_INCOME_MANAGER.INCOME
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncome(Double income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncomeStatus() {
        return incomeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @param incomeStatus the value for T_MIGU_INCOME_MANAGER.INCOME_STATUS
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeStatus(String incomeStatus) {
        this.incomeStatus = incomeStatus == null ? null : incomeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncomeOptionUrl() {
        return incomeOptionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @param incomeOptionUrl the value for T_MIGU_INCOME_MANAGER.INCOME_OPTION_URL
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeOptionUrl(String incomeOptionUrl) {
        this.incomeOptionUrl = incomeOptionUrl == null ? null : incomeOptionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @param incomeDate the value for T_MIGU_INCOME_MANAGER.INCOME_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setIncomeDate(String incomeDate) {
        this.incomeDate = incomeDate == null ? null : incomeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @return the value of T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public String getLasteDate() {
        return lasteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @param lasteDate the value for T_MIGU_INCOME_MANAGER.LASTE_DATE
     *
     * @mbg.generated Mon Jun 26 17:24:20 CST 2017
     */
    public void setLasteDate(String lasteDate) {
        this.lasteDate = lasteDate == null ? null : lasteDate.trim();
    }

    
	public String getAuditDept() {
		return auditDept;
	}

	public void setAuditDept(String auditDept) {
		this.auditDept = auditDept == null ? null : auditDept.trim();
	}

	public String getAuditPerson() {
		return auditPerson;
	}

	public void setAuditPerson(String auditPerson) {
		this.auditPerson = auditPerson == null ? null : auditPerson.trim();;
	}

	
	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Double getEstimateIncomeTax() {
		return estimateIncomeTax;
	}

	public void setEstimateIncomeTax(Double estimateIncomeTax) {
		this.estimateIncomeTax = estimateIncomeTax;
	}

	public Double getEstimateExclusiveTax() {
		return estimateExclusiveTax;
	}

	public void setEstimateExclusiveTax(Double estimateExclusiveTax) {
		this.estimateExclusiveTax = estimateExclusiveTax;
	}

	public Double getEstimateAmount() {
		return estimateAmount;
	}

	public void setEstimateAmount(Double estimateAmount) {
		this.estimateAmount = estimateAmount;
	}
	

	public Double getRealIncomeTax() {
		return realIncomeTax;
	}

	public void setRealIncomeTax(Double realIncomeTax) {
		this.realIncomeTax = realIncomeTax;
	}

	public Double getRealExclusiveTax() {
		return realExclusiveTax;
	}

	public void setRealExclusiveTax(Double realExclusiveTax) {
		this.realExclusiveTax = realExclusiveTax;
	}

	public Double getRealAmount() {
		return realAmount;
	}

	public void setRealAmount(Double realAmount) {
		this.realAmount = realAmount;
	}

	
	public String getIsNeedBill() {
		return isNeedBill;
	}

	public void setIsNeedBill(String isNeedBill) {
		this.isNeedBill = isNeedBill;
	}

	
	public String getBzCycle() {
		return bzCycle;
	}

	public void setBzCycle(String bzCycle) {
		this.bzCycle = bzCycle;
	}

	
	public String getBzCycleReal() {
		return bzCycleReal;
	}

	public void setBzCycleReal(String bzCycleReal) {
		this.bzCycleReal = bzCycleReal;
	}

	@Override
	public String toString() {
		return "MiguIncomeManager [incomeManagerId=" + incomeManagerId + ", cycle=" + cycle + ", projectId=" + projectId
				+ ", projectName=" + projectName + ", estimateIncome=" + estimateIncome + ", estimateExplain="
				+ estimateExplain + ", estimateOptionsUrl=" + estimateOptionsUrl + ", eastimateStatus="
				+ eastimateStatus + ", realIncome=" + realIncome + ", realStatus=" + realStatus + ", realExplain="
				+ realExplain + ", realOptionsUrl=" + realOptionsUrl + ", deferenceInIncome=" + deferenceInIncome
				+ ", billingType=" + billingType + ", taxpayer=" + taxpayer + ", billingStatus=" + billingStatus
				+ ", income=" + income + ", incomeStatus=" + incomeStatus + ", incomeOptionUrl=" + incomeOptionUrl
				+ ", incomeDate=" + incomeDate + ", lasteDate=" + lasteDate + ", rn=" + rn + ", auditDept=" + auditDept
				+ ", auditPerson=" + auditPerson + ", fileName=" + fileName + ", remark=" + remark + ", billingTime="
				+ billingTime + ", billingKey=" + billingKey + ", offset=" + offset + ", estimateIncomeTax="
				+ estimateIncomeTax + ", estimateExclusiveTax=" + estimateExclusiveTax + ", estimateAmount="
				+ estimateAmount + ", realIncomeTax=" + realIncomeTax + ", realExclusiveTax=" + realExclusiveTax
				+ ", realAmount=" + realAmount + ", isNeedBill=" + isNeedBill + ", getOffset()=" + getOffset()
				+ ", getBillingTime()=" + getBillingTime() + ", getBillingKey()=" + getBillingKey() + ", getRn()="
				+ getRn() + ", getIncomeManagerId()=" + getIncomeManagerId() + ", getCycle()=" + getCycle()
				+ ", getProjectId()=" + getProjectId() + ", getProjectName()=" + getProjectName()
				+ ", getEstimateIncome()=" + getEstimateIncome() + ", getEstimateExplain()=" + getEstimateExplain()
				+ ", getEstimateOptionsUrl()=" + getEstimateOptionsUrl() + ", getEastimateStatus()="
				+ getEastimateStatus() + ", getRealIncome()=" + getRealIncome() + ", getRealStatus()=" + getRealStatus()
				+ ", getRealExplain()=" + getRealExplain() + ", getRealOptionsUrl()=" + getRealOptionsUrl()
				+ ", getDeferenceInIncome()=" + getDeferenceInIncome() + ", getBillingType()=" + getBillingType()
				+ ", getTaxpayer()=" + getTaxpayer() + ", getBillingStatus()=" + getBillingStatus() + ", getIncome()="
				+ getIncome() + ", getIncomeStatus()=" + getIncomeStatus() + ", getIncomeOptionUrl()="
				+ getIncomeOptionUrl() + ", getIncomeDate()=" + getIncomeDate() + ", getLasteDate()=" + getLasteDate()
				+ ", getAuditDept()=" + getAuditDept() + ", getAuditPerson()=" + getAuditPerson() + ", getFileName()="
				+ getFileName() + ", getRemark()=" + getRemark() + ", getEstimateIncomeTax()=" + getEstimateIncomeTax()
				+ ", getEstimateExclusiveTax()=" + getEstimateExclusiveTax() + ", getEstimateAmount()="
				+ getEstimateAmount() + ", getRealIncomeTax()=" + getRealIncomeTax() + ", getRealExclusiveTax()="
				+ getRealExclusiveTax() + ", getRealAmount()=" + getRealAmount() + ", getIsNeedBill()="
				+ getIsNeedBill() + ", getClass()=" + getClass() + ", hashCode()=" + hashCode() + ", toString()="
				+ super.toString() + "]";
	}

	
		
}