package cn.migu.income.pojo;

import java.math.BigDecimal;

public class TMiguContract {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_PROJECT_CONTRCTOR
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conProjectContrctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_UNDERTAKE_DEPTNAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conUndertakeDeptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_NO
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_NUMBER
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private BigDecimal conNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_BIG_TYPE
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conBigType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_START_TIME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_END_TIME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_TYPE_PAYREC
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conTypePayrec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_CURRENCY_AMOUNT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private BigDecimal conCurrencyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_VENDOR_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conVendorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_VENDOR_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conVendorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_BANK_ABSTRCT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conBankAbstrct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_BANK_ACCOUNT_NUM
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conBankAccountNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_TAX_QUALIFIED
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conTaxQualified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_TAXAMOUNT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private BigDecimal conTaxamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.PROJECT_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_CONTRACT.CON_CAPITAL_NATURE_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    private String conCapitalNatureName;
    
    
    
    
    private String rn;
    

    public String getRn() {
		return rn;
	}

	public void setRn(String rn) {
		this.rn = rn;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_ID
     *
     * @return the value of T_MIGU_CONTRACT.CON_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConId() {
        return conId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_ID
     *
     * @param conId the value for T_MIGU_CONTRACT.CON_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConId(String conId) {
        this.conId = conId == null ? null : conId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_PROJECT_CONTRCTOR
     *
     * @return the value of T_MIGU_CONTRACT.CON_PROJECT_CONTRCTOR
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConProjectContrctor() {
        return conProjectContrctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_PROJECT_CONTRCTOR
     *
     * @param conProjectContrctor the value for T_MIGU_CONTRACT.CON_PROJECT_CONTRCTOR
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConProjectContrctor(String conProjectContrctor) {
        this.conProjectContrctor = conProjectContrctor == null ? null : conProjectContrctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_UNDERTAKE_DEPTNAME
     *
     * @return the value of T_MIGU_CONTRACT.CON_UNDERTAKE_DEPTNAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConUndertakeDeptname() {
        return conUndertakeDeptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_UNDERTAKE_DEPTNAME
     *
     * @param conUndertakeDeptname the value for T_MIGU_CONTRACT.CON_UNDERTAKE_DEPTNAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConUndertakeDeptname(String conUndertakeDeptname) {
        this.conUndertakeDeptname = conUndertakeDeptname == null ? null : conUndertakeDeptname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_NO
     *
     * @return the value of T_MIGU_CONTRACT.CON_NO
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConNo() {
        return conNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_NO
     *
     * @param conNo the value for T_MIGU_CONTRACT.CON_NO
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConNo(String conNo) {
        this.conNo = conNo == null ? null : conNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_NAME
     *
     * @return the value of T_MIGU_CONTRACT.CON_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConName() {
        return conName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_NAME
     *
     * @param conName the value for T_MIGU_CONTRACT.CON_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConName(String conName) {
        this.conName = conName == null ? null : conName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_NUMBER
     *
     * @return the value of T_MIGU_CONTRACT.CON_NUMBER
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public BigDecimal getConNumber() {
        return conNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_NUMBER
     *
     * @param conNumber the value for T_MIGU_CONTRACT.CON_NUMBER
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConNumber(BigDecimal conNumber) {
        this.conNumber = conNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_BIG_TYPE
     *
     * @return the value of T_MIGU_CONTRACT.CON_BIG_TYPE
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConBigType() {
        return conBigType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_BIG_TYPE
     *
     * @param conBigType the value for T_MIGU_CONTRACT.CON_BIG_TYPE
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConBigType(String conBigType) {
        this.conBigType = conBigType == null ? null : conBigType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_START_TIME
     *
     * @return the value of T_MIGU_CONTRACT.CON_START_TIME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConStartTime() {
        return conStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_START_TIME
     *
     * @param conStartTime the value for T_MIGU_CONTRACT.CON_START_TIME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConStartTime(String conStartTime) {
        this.conStartTime = conStartTime == null ? null : conStartTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_END_TIME
     *
     * @return the value of T_MIGU_CONTRACT.CON_END_TIME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConEndTime() {
        return conEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_END_TIME
     *
     * @param conEndTime the value for T_MIGU_CONTRACT.CON_END_TIME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConEndTime(String conEndTime) {
        this.conEndTime = conEndTime == null ? null : conEndTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_TYPE_PAYREC
     *
     * @return the value of T_MIGU_CONTRACT.CON_TYPE_PAYREC
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConTypePayrec() {
        return conTypePayrec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_TYPE_PAYREC
     *
     * @param conTypePayrec the value for T_MIGU_CONTRACT.CON_TYPE_PAYREC
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConTypePayrec(String conTypePayrec) {
        this.conTypePayrec = conTypePayrec == null ? null : conTypePayrec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_CURRENCY_AMOUNT
     *
     * @return the value of T_MIGU_CONTRACT.CON_CURRENCY_AMOUNT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public BigDecimal getConCurrencyAmount() {
        return conCurrencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_CURRENCY_AMOUNT
     *
     * @param conCurrencyAmount the value for T_MIGU_CONTRACT.CON_CURRENCY_AMOUNT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConCurrencyAmount(BigDecimal conCurrencyAmount) {
        this.conCurrencyAmount = conCurrencyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_VENDOR_ID
     *
     * @return the value of T_MIGU_CONTRACT.CON_VENDOR_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConVendorId() {
        return conVendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_VENDOR_ID
     *
     * @param conVendorId the value for T_MIGU_CONTRACT.CON_VENDOR_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConVendorId(String conVendorId) {
        this.conVendorId = conVendorId == null ? null : conVendorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_VENDOR_NAME
     *
     * @return the value of T_MIGU_CONTRACT.CON_VENDOR_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConVendorName() {
        return conVendorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_VENDOR_NAME
     *
     * @param conVendorName the value for T_MIGU_CONTRACT.CON_VENDOR_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConVendorName(String conVendorName) {
        this.conVendorName = conVendorName == null ? null : conVendorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_BANK_ABSTRCT
     *
     * @return the value of T_MIGU_CONTRACT.CON_BANK_ABSTRCT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConBankAbstrct() {
        return conBankAbstrct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_BANK_ABSTRCT
     *
     * @param conBankAbstrct the value for T_MIGU_CONTRACT.CON_BANK_ABSTRCT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConBankAbstrct(String conBankAbstrct) {
        this.conBankAbstrct = conBankAbstrct == null ? null : conBankAbstrct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_BANK_ACCOUNT_NUM
     *
     * @return the value of T_MIGU_CONTRACT.CON_BANK_ACCOUNT_NUM
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConBankAccountNum() {
        return conBankAccountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_BANK_ACCOUNT_NUM
     *
     * @param conBankAccountNum the value for T_MIGU_CONTRACT.CON_BANK_ACCOUNT_NUM
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConBankAccountNum(String conBankAccountNum) {
        this.conBankAccountNum = conBankAccountNum == null ? null : conBankAccountNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_TAX_QUALIFIED
     *
     * @return the value of T_MIGU_CONTRACT.CON_TAX_QUALIFIED
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConTaxQualified() {
        return conTaxQualified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_TAX_QUALIFIED
     *
     * @param conTaxQualified the value for T_MIGU_CONTRACT.CON_TAX_QUALIFIED
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConTaxQualified(String conTaxQualified) {
        this.conTaxQualified = conTaxQualified == null ? null : conTaxQualified.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_TAXAMOUNT
     *
     * @return the value of T_MIGU_CONTRACT.CON_TAXAMOUNT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public BigDecimal getConTaxamount() {
        return conTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_TAXAMOUNT
     *
     * @param conTaxamount the value for T_MIGU_CONTRACT.CON_TAXAMOUNT
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConTaxamount(BigDecimal conTaxamount) {
        this.conTaxamount = conTaxamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.PROJECT_ID
     *
     * @return the value of T_MIGU_CONTRACT.PROJECT_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.PROJECT_ID
     *
     * @param projectId the value for T_MIGU_CONTRACT.PROJECT_ID
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_CONTRACT.CON_CAPITAL_NATURE_NAME
     *
     * @return the value of T_MIGU_CONTRACT.CON_CAPITAL_NATURE_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public String getConCapitalNatureName() {
        return conCapitalNatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_CONTRACT.CON_CAPITAL_NATURE_NAME
     *
     * @param conCapitalNatureName the value for T_MIGU_CONTRACT.CON_CAPITAL_NATURE_NAME
     *
     * @mbggenerated Tue Jun 13 18:23:59 CST 2017
     */
    public void setConCapitalNatureName(String conCapitalNatureName) {
        this.conCapitalNatureName = conCapitalNatureName == null ? null : conCapitalNatureName.trim();
    }

	@Override
	public String toString() {
		return "TMiguContract [conId=" + conId + ", conProjectContrctor=" + conProjectContrctor
				+ ", conUndertakeDeptname=" + conUndertakeDeptname + ", conNo=" + conNo + ", conName=" + conName
				+ ", conNumber=" + conNumber + ", conBigType=" + conBigType + ", conStartTime=" + conStartTime
				+ ", conEndTime=" + conEndTime + ", conTypePayrec=" + conTypePayrec + ", conCurrencyAmount="
				+ conCurrencyAmount + ", conVendorId=" + conVendorId + ", conVendorName=" + conVendorName
				+ ", conBankAbstrct=" + conBankAbstrct + ", conBankAccountNum=" + conBankAccountNum
				+ ", conTaxQualified=" + conTaxQualified + ", conTaxamount=" + conTaxamount + ", projectId=" + projectId
				+ ", conCapitalNatureName=" + conCapitalNatureName + ", rn=" + rn + "]";
	}
    
    
}