package cn.migu.income.pojo;

public class TMiguPriceConfigHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.HISTORY_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String historyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_NAME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.SUBMIT_AUDIT_TIME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String submitAuditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.PERFORM_AUDIT_TIME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String performAuditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.AUDIT_RESULT
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String auditResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.HANDLING_SUGGESTION
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String handlingSuggestion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PRICE_CONFIG_HISTORY.PRICE_CONFIG_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    private String priceConfigId;
    
    private String rn;
    

    public String getRn() {
		return rn;
	}

	public void setRn(String rn) {
		this.rn = rn;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.HISTORY_ID
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.HISTORY_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getHistoryId() {
        return historyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.HISTORY_ID
     *
     * @param historyId the value for T_MIGU_PRICE_CONFIG_HISTORY.HISTORY_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setHistoryId(String historyId) {
        this.historyId = historyId == null ? null : historyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_ID
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_ID
     *
     * @param projectId the value for T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_NAME
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_NAME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_NAME
     *
     * @param projectName the value for T_MIGU_PRICE_CONFIG_HISTORY.PROJECT_NAME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.SUBMIT_AUDIT_TIME
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.SUBMIT_AUDIT_TIME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getSubmitAuditTime() {
        return submitAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.SUBMIT_AUDIT_TIME
     *
     * @param submitAuditTime the value for T_MIGU_PRICE_CONFIG_HISTORY.SUBMIT_AUDIT_TIME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setSubmitAuditTime(String submitAuditTime) {
        this.submitAuditTime = submitAuditTime == null ? null : submitAuditTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PERFORM_AUDIT_TIME
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.PERFORM_AUDIT_TIME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getPerformAuditTime() {
        return performAuditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PERFORM_AUDIT_TIME
     *
     * @param performAuditTime the value for T_MIGU_PRICE_CONFIG_HISTORY.PERFORM_AUDIT_TIME
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setPerformAuditTime(String performAuditTime) {
        this.performAuditTime = performAuditTime == null ? null : performAuditTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.AUDIT_RESULT
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.AUDIT_RESULT
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getAuditResult() {
        return auditResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.AUDIT_RESULT
     *
     * @param auditResult the value for T_MIGU_PRICE_CONFIG_HISTORY.AUDIT_RESULT
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setAuditResult(String auditResult) {
        this.auditResult = auditResult == null ? null : auditResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.HANDLING_SUGGESTION
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.HANDLING_SUGGESTION
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getHandlingSuggestion() {
        return handlingSuggestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.HANDLING_SUGGESTION
     *
     * @param handlingSuggestion the value for T_MIGU_PRICE_CONFIG_HISTORY.HANDLING_SUGGESTION
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setHandlingSuggestion(String handlingSuggestion) {
        this.handlingSuggestion = handlingSuggestion == null ? null : handlingSuggestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PRICE_CONFIG_ID
     *
     * @return the value of T_MIGU_PRICE_CONFIG_HISTORY.PRICE_CONFIG_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public String getPriceConfigId() {
        return priceConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PRICE_CONFIG_HISTORY.PRICE_CONFIG_ID
     *
     * @param priceConfigId the value for T_MIGU_PRICE_CONFIG_HISTORY.PRICE_CONFIG_ID
     *
     * @mbggenerated Thu Jun 22 14:15:38 CST 2017
     */
    public void setPriceConfigId(String priceConfigId) {
        this.priceConfigId = priceConfigId == null ? null : priceConfigId.trim();
    }

	@Override
	public String toString() {
		return "TMiguPriceConfigHistory [historyId=" + historyId + ", projectId=" + projectId + ", projectName="
				+ projectName + ", submitAuditTime=" + submitAuditTime + ", performAuditTime=" + performAuditTime
				+ ", auditResult=" + auditResult + ", handlingSuggestion=" + handlingSuggestion + ", priceConfigId="
				+ priceConfigId + ", rn=" + rn + "]";
	}
    
    
}