package cn.migu.income.pojo;

import java.util.Date;

public class TMiguProjectBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PROJECT_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PROJECT_NAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.INCOME_CLASS_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String incomeClassId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.INCOME_SECTION_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String incomeSectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PROJECT_USER_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String projectUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PROJECT_DEPT_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String projectDeptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.UPDATE_DATE
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.REQUISITION_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String requisitionFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.OA_SCREEN_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String oaScreenFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PRO_FILE_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String proFileFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.COMMENTS
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PROJECT_APPLY_USER_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String projectApplyUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.REQUISITION_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String requisitionFilepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.OA_SCREEN_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String oaScreenFilepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MIGU_PROJECT_BASE.PRO_FILE_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    private String proFileFilepath;
    
    
    //新增列表展示字段
    private String rn;
    
    private String incomeClassName;
    
    private String incomeSectionName;
    
    private String projectUserName;
    
    private String projectDeptName;
    
    private String priceConfig;
    
    private String budget;
    
    private String contract;
    
    private String projectApplyUserName;
  
   private String createDate;
   
   
    public String getCreateDate() {
	return createDate;
}

public void setCreateDate(String createDate) {
	this.createDate = createDate;
}

	public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PROJECT_ID
     *
     * @param projectId the value for T_MIGU_PROJECT_BASE.PROJECT_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.PROJECT_NAME
     *
     * @return the value of T_MIGU_PROJECT_BASE.PROJECT_NAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PROJECT_NAME
     *
     * @param projectName the value for T_MIGU_PROJECT_BASE.PROJECT_NAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.INCOME_CLASS_ID
     *
     * @return the value of T_MIGU_PROJECT_BASE.INCOME_CLASS_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getIncomeClassId() {
        return incomeClassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.INCOME_CLASS_ID
     *
     * @param incomeClassId the value for T_MIGU_PROJECT_BASE.INCOME_CLASS_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setIncomeClassId(String incomeClassId) {
        this.incomeClassId = incomeClassId == null ? null : incomeClassId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.INCOME_SECTION_ID
     *
     * @return the value of T_MIGU_PROJECT_BASE.INCOME_SECTION_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getIncomeSectionId() {
        return incomeSectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.INCOME_SECTION_ID
     *
     * @param incomeSectionId the value for T_MIGU_PROJECT_BASE.INCOME_SECTION_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setIncomeSectionId(String incomeSectionId) {
        this.incomeSectionId = incomeSectionId == null ? null : incomeSectionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.PROJECT_USER_ID
     *
     * @return the value of T_MIGU_PROJECT_BASE.PROJECT_USER_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getProjectUserId() {
        return projectUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PROJECT_USER_ID
     *
     * @param projectUserId the value for T_MIGU_PROJECT_BASE.PROJECT_USER_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProjectUserId(String projectUserId) {
        this.projectUserId = projectUserId == null ? null : projectUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.PROJECT_DEPT_ID
     *
     * @return the value of T_MIGU_PROJECT_BASE.PROJECT_DEPT_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getProjectDeptId() {
        return projectDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PROJECT_DEPT_ID
     *
     * @param projectDeptId the value for T_MIGU_PROJECT_BASE.PROJECT_DEPT_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProjectDeptId(String projectDeptId) {
        this.projectDeptId = projectDeptId == null ? null : projectDeptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.UPDATE_DATE
     *
     * @return the value of T_MIGU_PROJECT_BASE.UPDATE_DATE
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.UPDATE_DATE
     *
     * @param updateDate the value for T_MIGU_PROJECT_BASE.UPDATE_DATE
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.REQUISITION_FILENAME
     *
     * @return the value of T_MIGU_PROJECT_BASE.REQUISITION_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getRequisitionFilename() {
        return requisitionFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.REQUISITION_FILENAME
     *
     * @param requisitionFilename the value for T_MIGU_PROJECT_BASE.REQUISITION_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setRequisitionFilename(String requisitionFilename) {
        this.requisitionFilename = requisitionFilename == null ? null : requisitionFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.OA_SCREEN_FILENAME
     *
     * @return the value of T_MIGU_PROJECT_BASE.OA_SCREEN_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getOaScreenFilename() {
        return oaScreenFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.OA_SCREEN_FILENAME
     *
     * @param oaScreenFilename the value for T_MIGU_PROJECT_BASE.OA_SCREEN_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setOaScreenFilename(String oaScreenFilename) {
        this.oaScreenFilename = oaScreenFilename == null ? null : oaScreenFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.PRO_FILE_FILENAME
     *
     * @return the value of T_MIGU_PROJECT_BASE.PRO_FILE_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getProFileFilename() {
        return proFileFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PRO_FILE_FILENAME
     *
     * @param proFileFilename the value for T_MIGU_PROJECT_BASE.PRO_FILE_FILENAME
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProFileFilename(String proFileFilename) {
        this.proFileFilename = proFileFilename == null ? null : proFileFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.COMMENTS
     *
     * @return the value of T_MIGU_PROJECT_BASE.COMMENTS
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.COMMENTS
     *
     * @param comments the value for T_MIGU_PROJECT_BASE.COMMENTS
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.PROJECT_APPLY_USER_ID
     *
     * @return the value of T_MIGU_PROJECT_BASE.PROJECT_APPLY_USER_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getProjectApplyUserId() {
        return projectApplyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PROJECT_APPLY_USER_ID
     *
     * @param projectApplyUserId the value for T_MIGU_PROJECT_BASE.PROJECT_APPLY_USER_ID
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProjectApplyUserId(String projectApplyUserId) {
        this.projectApplyUserId = projectApplyUserId == null ? null : projectApplyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.REQUISITION_FILEPATH
     *
     * @return the value of T_MIGU_PROJECT_BASE.REQUISITION_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getRequisitionFilepath() {
        return requisitionFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.REQUISITION_FILEPATH
     *
     * @param requisitionFilepath the value for T_MIGU_PROJECT_BASE.REQUISITION_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setRequisitionFilepath(String requisitionFilepath) {
        this.requisitionFilepath = requisitionFilepath == null ? null : requisitionFilepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.OA_SCREEN_FILEPATH
     *
     * @return the value of T_MIGU_PROJECT_BASE.OA_SCREEN_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getOaScreenFilepath() {
        return oaScreenFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.OA_SCREEN_FILEPATH
     *
     * @param oaScreenFilepath the value for T_MIGU_PROJECT_BASE.OA_SCREEN_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setOaScreenFilepath(String oaScreenFilepath) {
        this.oaScreenFilepath = oaScreenFilepath == null ? null : oaScreenFilepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MIGU_PROJECT_BASE.PRO_FILE_FILEPATH
     *
     * @return the value of T_MIGU_PROJECT_BASE.PRO_FILE_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public String getProFileFilepath() {
        return proFileFilepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MIGU_PROJECT_BASE.PRO_FILE_FILEPATH
     *
     * @param proFileFilepath the value for T_MIGU_PROJECT_BASE.PRO_FILE_FILEPATH
     *
     * @mbggenerated Fri Jun 09 09:47:18 CST 2017
     */
    public void setProFileFilepath(String proFileFilepath) {
        this.proFileFilepath = proFileFilepath == null ? null : proFileFilepath.trim();
    }

	public String getIncomeClassName() {
		return incomeClassName;
	}

	public void setIncomeClassName(String incomeClassName) {
		this.incomeClassName = incomeClassName;
	}

	public String getIncomeSectionName() {
		return incomeSectionName;
	}

	public void setIncomeSectionName(String incomeSectionName) {
		this.incomeSectionName = incomeSectionName;
	}

	public String getProjectUserName() {
		return projectUserName;
	}

	public void setProjectUserName(String projectUserName) {
		this.projectUserName = projectUserName;
	}

	public String getProjectDeptName() {
		return projectDeptName;
	}

	public void setProjectDeptName(String projectDeptName) {
		this.projectDeptName = projectDeptName;
	}

	public String getRn() {
		return rn;
	}

	public void setRn(String rn) {
		this.rn = rn;
	}


	public String getPriceConfig() {
		return priceConfig;
	}

	public void setPriceConfig(String priceConfig) {
		this.priceConfig = priceConfig;
	}

	public String getBudget() {
		return budget;
	}

	public void setBudget(String budget) {
		this.budget = budget;
	}

	public String getContract() {
		return contract;
	}

	public void setContract(String contract) {
		this.contract = contract;
	}

	public String getProjectApplyUserName() {
		return projectApplyUserName;
	}

	public void setProjectApplyUserName(String projectApplyUserName) {
		this.projectApplyUserName = projectApplyUserName;
	}

	@Override
	public String toString() {
		return "TMiguProjectBase [projectId=" + projectId + ", projectName=" + projectName + ", incomeClassId="
				+ incomeClassId + ", incomeSectionId=" + incomeSectionId + ", projectUserId=" + projectUserId
				+ ", projectDeptId=" + projectDeptId + ", updateDate=" + updateDate + ", requisitionFilename="
				+ requisitionFilename + ", oaScreenFilename=" + oaScreenFilename + ", proFileFilename="
				+ proFileFilename + ", comments=" + comments + ", projectApplyUserId=" + projectApplyUserId
				+ ", requisitionFilepath=" + requisitionFilepath + ", oaScreenFilepath=" + oaScreenFilepath
				+ ", proFileFilepath=" + proFileFilepath + ", rn=" + rn + ", incomeClassName=" + incomeClassName
				+ ", incomeSectionName=" + incomeSectionName + ", projectUserName=" + projectUserName
				+ ", projectDeptName=" + projectDeptName + ", priceConfig=" + priceConfig + ", budget=" + budget
				+ ", contract=" + contract + ", projectApplyUserName=" + projectApplyUserName + "]";
	}
	
	
	
	
    
    
}