package com.gscx.ssm.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MiguIncomeDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public MiguIncomeDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIncomeDetailIdIsNull() {
            addCriterion("INCOME_DETAIL_ID is null");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdIsNotNull() {
            addCriterion("INCOME_DETAIL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdEqualTo(BigDecimal value) {
            addCriterion("INCOME_DETAIL_ID =", value, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdNotEqualTo(BigDecimal value) {
            addCriterion("INCOME_DETAIL_ID <>", value, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdGreaterThan(BigDecimal value) {
            addCriterion("INCOME_DETAIL_ID >", value, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INCOME_DETAIL_ID >=", value, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdLessThan(BigDecimal value) {
            addCriterion("INCOME_DETAIL_ID <", value, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INCOME_DETAIL_ID <=", value, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdIn(List<BigDecimal> values) {
            addCriterion("INCOME_DETAIL_ID in", values, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdNotIn(List<BigDecimal> values) {
            addCriterion("INCOME_DETAIL_ID not in", values, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCOME_DETAIL_ID between", value1, value2, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeDetailIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INCOME_DETAIL_ID not between", value1, value2, "incomeDetailId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdIsNull() {
            addCriterion("INCOME_MANAGER_ID is null");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdIsNotNull() {
            addCriterion("INCOME_MANAGER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdEqualTo(String value) {
            addCriterion("INCOME_MANAGER_ID =", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdNotEqualTo(String value) {
            addCriterion("INCOME_MANAGER_ID <>", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdGreaterThan(String value) {
            addCriterion("INCOME_MANAGER_ID >", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdGreaterThanOrEqualTo(String value) {
            addCriterion("INCOME_MANAGER_ID >=", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdLessThan(String value) {
            addCriterion("INCOME_MANAGER_ID <", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdLessThanOrEqualTo(String value) {
            addCriterion("INCOME_MANAGER_ID <=", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdLike(String value) {
            addCriterion("INCOME_MANAGER_ID like", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdNotLike(String value) {
            addCriterion("INCOME_MANAGER_ID not like", value, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdIn(List<String> values) {
            addCriterion("INCOME_MANAGER_ID in", values, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdNotIn(List<String> values) {
            addCriterion("INCOME_MANAGER_ID not in", values, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdBetween(String value1, String value2) {
            addCriterion("INCOME_MANAGER_ID between", value1, value2, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andIncomeManagerIdNotBetween(String value1, String value2) {
            addCriterion("INCOME_MANAGER_ID not between", value1, value2, "incomeManagerId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdIsNull() {
            addCriterion("PRICE_CONFIG_INFO_ID is null");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdIsNotNull() {
            addCriterion("PRICE_CONFIG_INFO_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdEqualTo(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID =", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdNotEqualTo(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID <>", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdGreaterThan(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID >", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID >=", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdLessThan(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID <", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdLessThanOrEqualTo(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID <=", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdLike(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID like", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdNotLike(String value) {
            addCriterion("PRICE_CONFIG_INFO_ID not like", value, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdIn(List<String> values) {
            addCriterion("PRICE_CONFIG_INFO_ID in", values, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdNotIn(List<String> values) {
            addCriterion("PRICE_CONFIG_INFO_ID not in", values, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdBetween(String value1, String value2) {
            addCriterion("PRICE_CONFIG_INFO_ID between", value1, value2, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andPriceConfigInfoIdNotBetween(String value1, String value2) {
            addCriterion("PRICE_CONFIG_INFO_ID not between", value1, value2, "priceConfigInfoId");
            return (Criteria) this;
        }

        public Criteria andSellingPriceIsNull() {
            addCriterion("SELLING_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSellingPriceIsNotNull() {
            addCriterion("SELLING_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSellingPriceEqualTo(BigDecimal value) {
            addCriterion("SELLING_PRICE =", value, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceNotEqualTo(BigDecimal value) {
            addCriterion("SELLING_PRICE <>", value, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceGreaterThan(BigDecimal value) {
            addCriterion("SELLING_PRICE >", value, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SELLING_PRICE >=", value, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceLessThan(BigDecimal value) {
            addCriterion("SELLING_PRICE <", value, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SELLING_PRICE <=", value, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceIn(List<BigDecimal> values) {
            addCriterion("SELLING_PRICE in", values, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceNotIn(List<BigDecimal> values) {
            addCriterion("SELLING_PRICE not in", values, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SELLING_PRICE between", value1, value2, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andSellingPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SELLING_PRICE not between", value1, value2, "sellingPrice");
            return (Criteria) this;
        }

        public Criteria andPorductNumberIsNull() {
            addCriterion("PORDUCT_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPorductNumberIsNotNull() {
            addCriterion("PORDUCT_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPorductNumberEqualTo(BigDecimal value) {
            addCriterion("PORDUCT_NUMBER =", value, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberNotEqualTo(BigDecimal value) {
            addCriterion("PORDUCT_NUMBER <>", value, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberGreaterThan(BigDecimal value) {
            addCriterion("PORDUCT_NUMBER >", value, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PORDUCT_NUMBER >=", value, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberLessThan(BigDecimal value) {
            addCriterion("PORDUCT_NUMBER <", value, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PORDUCT_NUMBER <=", value, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberIn(List<BigDecimal> values) {
            addCriterion("PORDUCT_NUMBER in", values, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberNotIn(List<BigDecimal> values) {
            addCriterion("PORDUCT_NUMBER not in", values, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PORDUCT_NUMBER between", value1, value2, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andPorductNumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PORDUCT_NUMBER not between", value1, value2, "porductNumber");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 17 11:21:09 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_MIGU_INCOME_DETAIL
     *
     * @mbg.generated Mon Jul 17 11:21:09 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}