package cn.migu.income.dao;

import java.util.List;
import java.util.Map;

import cn.migu.income.pojo.MiguUsers;

public interface MiguUsersMapper {
    
    int selectCount(Map<String, Object> param) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_USERS
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    int deleteByPrimaryKey(String userId) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_USERS
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    int insert(MiguUsers record) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_USERS
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    int insertSelective(MiguUsers record) throws Exception;

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_USERS
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    MiguUsers selectByPrimaryKey(String userId) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MIGU_USERS
     *
     * @mbggenerated Wed Dec 30 17:01:57 CST 2015
     */
    MiguUsers selectOne(MiguUsers user) throws Exception;


    
    int updateByPrimaryKeySelective(MiguUsers record) throws Exception;

    
    int updateByPrimaryKey(MiguUsers record) throws Exception;
    
    /**
     * 查询所有用户列表
     * @param param
     * @return
     */
    public List<MiguUsers> queryAllUserList(Map<String, Object> param) throws Exception;
    
    
    /**
     * 根据用户名和手机号查询用户
     * @param userName
     * @param msisdn
     * @return
     */
    public List<MiguUsers> queryUserByDn(Map<String, String> param) throws Exception;
    
    /**
     * 增加用户
     * @param user
     * @return
     */
    int addUser(Map<String, Object> map) throws Exception;
    
    /**
     * 删除用户
     * @param userIds
     * @return
     */
    public String deleteUser(String userIds) throws Exception;
    
    public int deleteUserById(String[] userIds) throws Exception;
    
    /**
     * 重置密码
     * @param userId
     * @param password
     * @return
     */
    public int resetPwd(Map<String, Object> param) throws Exception;
    
    public int modUserPassword(MiguUsers user) throws Exception;
    
    MiguUsers selectOldPwdByUser(String userId) throws Exception;    
    
    public List<MiguUsers> queryDeptUserList(Map<String, Object> param) throws Exception;
    
    List<MiguUsers> queryPriceCommitteeUser() throws Exception;
    /**
     * 查询财务会计
     */
    List<MiguUsers> queryUserByRole(String deptId);
    
}